name: Laravel
on: push
jobs:
  laravel-checks:
    runs-on: ubuntu-latest
    container:
      image: thomasowow/laravel-php:7.4
    steps:
    - uses: actions/checkout@v2
    - run: ls -l
    - run: printenv
    - name: Yarn
      shell: bash
      run: |
        yarn
